# Generated by Django 5.1.1 on 2025-01-24 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_carouselimage_remove_job_employer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='posted_on',
            new_name='posted_date',
        ),
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
