# Generated by Django 5.1.1 on 2025-01-24 19:05
from django.utils import timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_posted_on_job_posted_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
