# Generated by Django 5.1.1 on 2025-02-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_application_email_application_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
